services:
  wololo-server:
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    develop:
      watch:
        - path: ./server
          action: rebuild
    environment:
      - FRONT_URL=http://localhost:5173
    ports:
      - "3000:3000"

  wololo-client:
    depends_on:
      - wololo-server
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./client/
      dockerfile: ./Dockerfile.dev
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: ./app/src
        - path: ./client/package-lock.json
          action: rebuild
    command: npm run dev -- --host
    ports:
      - "5173:5173"

networks:
  wololo: {}
